---
builds:
  - id: demo-app
    goos: &goos-defs
      - linux
    goarch: &goarch-defs
      - amd64
    env:
      - CGO_ENABLED=0
    binary: demo-app

archives:
  - id: demo-app
    builds:
      - demo-app
    name_template: "demo-app_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements: &replacements
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
