name: Hello Release

on:
  push:
    branches:
      - 'release-*'

jobs:
  say_hello:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@master
      - name: Print ref
        run: echo "ref is $GITHUB_REF"
      - name: Say Hello
        run: echo "Hello World!"
        