name: Build and push VMware Event Router Pre-Release to Docker Hub

on:
  push:
    branches:
      - release-*

defaults:
  run:
    shell: bash
    working-directory: ./vmware-event-router

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source (master branch)
        uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: test, build and push image
        env: 
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
        run: |
          echo "Building pre-release image with version $VERSION"
          make
