name: Protect Master Branch

# This workflow is triggered on PRs to the master branch
on:
  pull_request:
    branches:
      - master

# Perform "exit 1"
jobs:
  protect:
    name: Reject
    # This job runs on Linux
    runs-on: ubuntu-latest
    # sanity check
    if: github.event_name == 'pull_request' && github.base_ref == 'master'
    steps:
      - name: Must Exit
        run: exit 1
