name: VMware Event Router Linting

# triggered on every push and PRs but only when changes inside
# vmware-event-router (sub)dir(s)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'vmware-event-router/**'
  push:
    paths:
      - 'vmware-event-router/**'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest

          # Optional: working directory, useful for monorepos
          working-directory: vmware-event-router

          # Optional: golangci-lint command line arguments.
          args: --build-tags unit,integration -v

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true