name: Unit tests

on:
  pull_request:
    paths:
      - 'vmware-event-router/**'

defaults:
  run:
    shell: bash
    working-directory: ./vmware-event-router

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@master
      - name: run unit tests
        run: make tests
          
